### ISSUE TITLE
getTypeReference(TypeReference) returns unexpected result when a type has multiple parameters

### ISSUE THREAD

**Issue by tiwatsuka** [INRIA/spoon#3913] opened 2021-05-06 16:03 UTC
# Abstract
`getTypeReference(TypeReference)` in `spoon.support.compiler.jdt.ReferenceBuilder` returns unexpected result when a type has multiple parameters. It can cause exception when building a model.

# Cause of the problem and mitigation

https://github.com/INRIA/spoon/blob/c3ed4be2a825588c8253418caa4905336c4e985f/src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java#L660

When a type has multiple parameters, the result of `res.toStringDebug()` contains a whitespace after commas between the parameters (e.g., `Foo<?, ?>`). In contrast, `nameParameterized` does not contain any whitespaces (e.g., `Foo<?,?>`).  To my understanding, `replace(", ?", ",?")` was inserted to fill the gap. However, it's worked only when the parameters are wildcard. Therefore, it should be `replace(", ", ",")` rather than `replace(", ?", ",?")`.

# How to reproduce

I couldn't create a minimum code to reproduce the problem. I found this problem when I try to build a model from following code with no class path mode.
https://github.com/google/guava/blob/559e1ac1359e8d5dc0941aa72691698185d65407/android/guava/src/com/google/common/collect/Maps.java

**Comment by andrewbwogi** [comment] 2021-05-10 15:43
Hi @tiwatsuka, can you give an example of how you are using `ReferenceBuilder` and what the unexpected result is? Perhaps the code that is causing an exception when you build the model?

**Comment by slarse** [comment] 2021-05-31 09:46
I'm looking into this.

**Comment by slarse** [comment] 2021-05-31 12:43
I tinkered with this a little bit before lunch and found minimal test input to reproduce it:

```java
public final class Test<K,V> {
    public void test() {
        new Test.GenericType<K, V>(this) {
        };
    }

    static class GenericType<K, V> {
    }
}
```

There are a few important details to trigger the behavior:

1. There has to be some form of error with the constructor invocation, such that the proper binding is not resolved (e.g. constructor does not exist or is not on the classpath). In the above example, there's no constructor that takes parameters, yet it's invoked with `this`.
    - If there is no problem with the constructor invocation, then the behavior is not triggered as the binding is resolved by JDT, and Spoon does not have to do any heavy lifting.
2. There must be a creation of an anonymous class. Otherwise, for some reason, JDT creates an `AllocationExpression` instead of a `QualifiedAllocationExpression` (see point 4), which traverses a different code path.
3. The type that is subtyped with the anonymous class must be referenced with a qualified _within the type_ (here, `Test.GenericType`).
    - Not to be mixed up with fully qualified name, just qualified within the enclosing type.

This causes a pretty weird state in JDT where we have a `QualifiedAllocationExpression` for which the binding is unknown, but the type can be without it being a problem reference, probably due to the creation of the anonymous type. To summarize, this is a "noclasspath" problem that only occurs on creation of anonymous types such that the constructor used for some reason cannot be resolved to a binding.

The fix suggested by @tiwatsuka does solve the symptoms, but I'm not yet entirely sure that's where the problem needs to be solved. That thing needs to be fixed regardless, but I need to dig a little more to determine if it solves the problem here, or just hides it.

**Closed** 2021-06-01 05:44 UTC

**Comment by slarse** [comment] 2021-06-01 06:17
This is now tfixed, thanks for reporting it @tiwatsuka
