### ISSUE TITLE
[Bug]: CtType.getMethods returns an empty set()

### ISSUE THREAD

**Issue by djaekim** [INRIA/spoon#5132] opened 2023-03-04 17:47 UTC
### Describe the bug

Running CtType.getMethods() on this specific [commit](https://github.com/apache/maven/blob/706d9319f14b507f3c3deeba4eeda1a51a531c9b/maven-core/src/test/java/org/apache/maven/project/AbstractMavenProjectTestCase.java) returns empty set(), despite existing methods.

### Source code you are trying to analyze/transform

```Java
Check this [commit](https://github.com/apache/maven/blob/706d9319f14b507f3c3deeba4eeda1a51a531c9b/maven-core/src/test/java/org/apache/maven/project/AbstractMavenProjectTestCase.java) returns empty set(), despite existing method
```

### Source code for your Spoon processing

```Java
this.laucher = new Launcher();
laucher.getEnvironment().setCommentEnabled(false);
laucher.getEnvironment().setIgnoreDuplicateDeclarations(true);
laucher.getEnvironment().setAutoImports(true);
laucher.getEnvironment().setIgnoreSyntaxErrors(true);
laucher.getEnvironment().setShouldCompile	(true);
laucher.addInputResource("Maven");
laucher.buildModel();
model = laucher.getModel();

for (CtType c : model.getElements(new TypeFilter<CtType<?>>(CtType.class))) {
    if (c.getQualifiedName().contains("org.apache.maven.project.AbstractMavenProjectTestCase")){
       System.out.println(c.getMethods());
    }
}
```

### Actual output

```Java
There are methods in this file, but spoon gives an empty set().
```

### Expected output

```Java
Should process methods in the file.
```

### Spoon Version

10.2.0

### JVM Version

18

### What operating system are you using?

Windows 10

**Comment by algomaster99** [comment] 2023-03-06 13:26
Hi @djaekim! I am unable to reproduce this. I am running Linux, but the different OS should not matter. The only possible rectification I can suggest is double-checking the path to the file you are passing to `launcher.addInputResource`.

**Comment by djaekim** [comment] 2023-03-06 13:54
Hi @algomaster99, I was wondering whether you provided the entire project folder or the file? I ran into this error when I put the entire folder and select the file based on if name matches. However, as you said, bug doesn't exist with file input.

**Comment by algomaster99** [comment] 2023-03-07 15:31
Yes, I was importing the single file itself.

Classes with the same fully qualified name in a multi-module project should be avoided. Classloader will only load one of them. Although, it does not matter here since these are test classes. I would suggest you load the sub-modules separately.

**Comment by djaekim** [comment] 2023-03-07 15:35
Hi, thank you for the reply.

I will do what you suggested. However, the methods still should not be empty. Seems suspicious.

**Comment by algomaster99** [comment] 2023-03-07 17:37
@djaekim I get all the 9 methods in the [second file (maven-compat)](https://github.com/apache/maven/blob/c1dfb947b509e195c75d4275a113598cf3063c3e/maven-compat/src/test/java/org/apache/maven/project/AbstractMavenProjectTestCase.java).

**Comment by djaekim** [comment] 2023-03-07 18:17
Did you run it on the entire folder or just submodule?

**Comment by algomaster99** [comment] 2023-03-07 18:21
I run it on the entire project, from the root module.

**Comment by algomaster99** [comment] 2023-04-25 21:58
@djaekim Hi! Can you close this if this was resolved?

**Closed** 2023-08-27 21:24 UTC
Labels: bug
