### ISSUE TITLE
Non blocking issue : spoon.Launcher "cannot determine runtime types" caused by internal NPE

### ISSUE THREAD

**Issue by ttben** [INRIA/spoon#627] opened 2016-04-25 09:36 UTC
Hi !

I'm trying to generate getter and setter methods for each field of an annotated Class.
In my custom processor, I am building a "add" method if the field is assignable from "List".

The code is given below

`
if(field.getType().isAssignableFrom(getFactory().Type().createReference(List.class))){
				//	Generate add method}
`

This line will generate a `NullPointerException ` and cause a 

> ERROR spoon.Launcher - cannot determine runtime types for 'java.lang.Iterable' and 'example.VariationPoint'

The NPE is fired  `at spoon.reflect.factory.TypeFactory.createReference(TypeFactory.java:129)
`

_Note : VariationPoint is a type of a field. It is part of my project._

The weird part is that a `mvn clean install` will **success** and the generated code is **correct**.

Any idea ?
Thanks :)

**Comment by GerardPaligot** [comment] 2016-04-25 15:43
I don't understand, `mvn clean install` works and the generated source code is correct. You get your error with your IDE?

Which version of Spoon do you use?

**Comment by ttben** [comment] 2016-04-25 18:02
When you execute `mvn clean install`, some errors are constantly fired but the build is still successful and the generated code is correct.

Spoon is properly triggered, my processor are properly detected and executed.

Since the build is declared as "successful", I'm just asking why those errors are fired ?

I have a direct dependency on the `spoon-maven-plugin` in `v2.2` which seems to use spoon `v.4.3.0`.

I copy paste a part of the stack trace on a `mvn clean install` command below if you need more information just let me know :

`[INFO] --- spoon-maven-plugin:2.2:generate (default) @ sandbox ---
2016-04-25 19:47:02,281 INFO spoon.support.StandardEnvironment - Spoon version 4.3.0
2016-04-25 19:47:02,283 INFO spoon.support.StandardEnvironment - running Spoon...
2016-04-25 19:47:02,283 INFO spoon.support.StandardEnvironment - start processing...
2016-04-25 19:47:03,460 INFO spoon.support.StandardEnvironment - processor.DeclareConceptProcessor
2016-04-25 19:47:03,516 ERROR spoon.Launcher - cannot determine runtime types for 'java.lang.Iterable' and 'example.VariationPoint'
java.lang.NullPointerException
        at spoon.reflect.factory.TypeFactory.createReference(TypeFactory.java:129)
        at spoon.support.reflect.reference.CtTypeReferenceImpl.isSubtypeOf(CtTypeReferenceImpl.java:279)
        at spoon.support.reflect.reference.CtTypeReferenceImpl.isSubtypeOf(CtTypeReferenceImpl.java:275)
        at spoon.support.reflect.reference.CtTypeReferenceImpl.isSubtypeOf(CtTypeReferenceImpl.java:275)
        at spoon.support.reflect.reference.CtTypeReferenceImpl.isAssignableFrom(CtTypeReferenceImpl.java:211)
        at processor.DeclareConceptProcessor.process(DeclareConceptProcessor.java:40)
        at processor.DeclareConceptProcessor.process(DeclareConceptProcessor.java:15)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:93)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:65)
        at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:583)
        at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:47)
       `

**Comment by GerardPaligot** [comment] 2016-04-25 18:09
Can you specify the latest version of Spoon in the configuration of the plugin maven:

```xml
<plugin>
  <groupId>fr.inria.gforge.spoon</groupId>
  <artifactId>spoon-maven-plugin</artifactId>
  <version>2.2</version>
  <executions>
    <execution>
      <phase>generate-sources</phase>
      <goals>
        <goal>generate</goal>
      </goals>
    </execution>
  </executions>
  <dependencies>
    <dependency>
      <groupId>fr.inria.gforge.spoon</groupId>
      <artifactId>spoon-core</artifactId>
      <version>5.1.0</version>
    </dependency>
  </dependencies>
</plugin>
```

**Comment by ttben** [comment] 2016-04-25 18:33
I just specified to use `v5.1.0` of spoon. The described behavior persist.

Stack trace below

> [INFO] --- spoon-maven-plugin:2.2:generate (default) @ sandbox ---
2016-04-25 20:32:03,961 INFO spoon.support.StandardEnvironment - Spoon version 5.1.0
2016-04-25 20:32:03,962 INFO spoon.support.StandardEnvironment - running Spoon...
2016-04-25 20:32:03,962 INFO spoon.support.StandardEnvironment - start processing...
2016-04-25 20:32:04,704 WARN spoon.support.StandardEnvironment - warning: Concept found at example.Constraint.(Constraint.java:6)
2016-04-25 20:32:04,706 WARN spoon.support.StandardEnvironment - warning: Building a setter to field Start on class : Constraint at example.Constraint.(Constraint.java:6)
2016-04-25 20:32:04,708 ERROR spoon.Launcher - cannot determine runtime types for 'java.lang.Iterable' and 'example.VariationPoint'
java.lang.NullPointerException
        at spoon.reflect.factory.TypeFactory.createReference(TypeFactory.java:132)
        at spoon.support.reflect.reference.CtTypeReferenceImpl.isSubtypeOf(CtTypeReferenceImpl.java:251)
        at spoon.support.reflect.reference.CtTypeReferenceImpl.isSubtypeOf(CtTypeReferenceImpl.java:247)
        at spoon.support.reflect.reference.CtTypeReferenceImpl.isSubtypeOf(CtTypeReferenceImpl.java:247)
        at spoon.support.reflect.reference.CtTypeReferenceImpl.isAssignableFrom(CtTypeReferenceImpl.java:183)
        at processor.DeclareConceptProcessor.process(DeclareConceptProcessor.java:40)

**Comment by GerardPaligot** [comment] 2016-04-26 09:42
Well, I reproduce your bug and I fixed it when I add the class in my spoon source path.

Can you execute the plugin in debug mode (`<debug>true</debug>` in the `<configuration>` element) and check that your classes are well in the input sources specified in your logs?

**Comment by ttben** [comment] 2016-04-26 12:06
> Can you execute the plugin in debug mode (<debug>true</debug> in the <configuration> element) and check that your classes are well in the input sources specified in your logs?

I don't understand what am I looking for.

> check that your classes are well in the input sources specified in your logs
My input sources are in the same maven module that depends on `spoon-maven-plugin`.
Plus `java.lang.Iterable` is a part of the error.

What can I do ?

**Comment by GerardPaligot** [comment] 2016-04-27 11:46
Your bug is weird. Do you have something somewhere to reproduce it?

**Comment by ttben** [comment] 2016-04-27 12:51
I can't reproduce this bug on a tiny quick example sorry
I'll tell you if this behavior disappears

**Comment by arnobl** [comment] 2016-05-04 08:14
Hi,
I think I have the same problem.
I commited a use case that reproduces the issue, see:
https://github.com/diverse-project/InspectorGuidget/blob/master/sources/InspectorGuidgetToolSuite/inspectorguidget.core/src/test/java/fr/inria/diverse/torgen/inspectorguidget/test/TestBugSpoonRuntimeTypes.java
and the analysed Java code:
https://github.com/diverse-project/InspectorGuidget/blob/master/sources/InspectorGuidgetToolSuite/inspectorguidget.core/src/test/resources/java/SpoonTestCode.java

Here is the output I have when executing the test:
ERROR spoon.Launcher - cannot determine runtime types for 'java.lang.Object' and 'foo.FooAbs'
java.lang.NullPointerException
	at spoon.reflect.factory.TypeFactory.createReference(TypeFactory.java:132)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.isSubtypeOf(CtTypeReferenceImpl.java:251)
	at spoon.support.reflect.reference.CtExecutableReferenceImpl.isOverriding(CtExecutableReferenceImpl.java:230)
	at spoon.reflect.visitor.filter.InvocationFilter.matches(InvocationFilter.java:54)
	at spoon.reflect.visitor.filter.InvocationFilter.matches(InvocationFilter.java:28)
	at spoon.reflect.visitor.QueryVisitor.scan(QueryVisitor.java:55)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:134)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:273)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:46)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
	at spoon.reflect.visitor.QueryVisitor.scan(QueryVisitor.java:61)
	at spoon.reflect.visitor.CtScanner.visitCtConstructor(CtScanner.java:328)
	at spoon.support.reflect.declaration.CtConstructorImpl.accept(CtConstructorImpl.java:46)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
	at spoon.reflect.visitor.QueryVisitor.scan(QueryVisitor.java:61)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:134)
	at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:308)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
	at spoon.reflect.visitor.QueryVisitor.scan(QueryVisitor.java:61)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:134)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:583)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:46)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
	at spoon.reflect.visitor.QueryVisitor.scan(QueryVisitor.java:61)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:134)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:582)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:46)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
	at spoon.reflect.visitor.QueryVisitor.scan(QueryVisitor.java:61)
	at spoon.reflect.visitor.Query.getElements(Query.java:70)
	at spoon.support.reflect.declaration.CtElementImpl.getElements(CtElementImpl.java:330)
	at fr.inria.diverse.torgen.inspectorguidget.test.TestProcessor.process(TestBugSpoonRuntimeTypes.java:20)
	at fr.inria.diverse.torgen.inspectorguidget.test.TestProcessor.process(TestBugSpoonRuntimeTypes.java:1)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:92)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:64)
	at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:309)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:64)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:583)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:46)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:64)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:582)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:46)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
	at spoon.support.QueueProcessingManager.process(QueueProcessingManager.java:142)
	at spoon.support.QueueProcessingManager.process(QueueProcessingManager.java:132)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.process(JDTBasedSpoonCompiler.java:238)
	at fr.inria.diverse.torgen.inspectorguidget.test.TestBugSpoonRuntimeTypes.testSpoon(TestBugSpoonRuntimeTypes.java:31)

**Comment by remal** [comment] 2016-05-11 15:07
Same problem for me.

Reason is inside class CtTypeReferenceImpl and method isSubtypeOf(CtTypeReference<?> type). When you calling actualSubType.getSuperclass(), you should check, that super class is not null.

**Comment by monperrus** [comment] 2016-05-11 15:27
does it happen with the latest snapshot?

**Comment by arnobl** [comment] 2016-05-11 15:35
It does not happen with spoon-core-5.2.0-20160510.235237-48 anymore. It was not the case one week ago.
I have several others tests that now fail with this snapshot but this is another story ;)

**Comment by monperrus** [comment] 2016-05-11 15:38
cool.

let's wait for the other story then :-)

**Comment by monperrus** [comment] 2016-05-31 16:06
should we close this issue if fixed in SNAPSHOT?

**Comment by arnobl** [comment] 2016-06-01 18:23
You can close the report IMO.

**Comment by arnobl** [comment] 2016-06-06 09:41
Well, I just had the problem using the latest 5.2-SNAPSHOT version:
java.lang.NullPointerException
	at spoon.reflect.factory.TypeFactory.createReference(TypeFactory.java:139)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.isSubtypeOf(CtTypeReferenceImpl.java:257)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.isSubtypeOf(CtTypeReferenceImpl.java:253)

It seems that a null super class is provided to 'createReference' that does not check for nullity.

**Comment by tdurieux** [comment] 2016-06-06 11:57
I don't know how  it is possible because the line `CtTypeReferenceImpl.java:257` is protected by a catch `Exception` (but the exception is logged).

**Comment by arnobl** [comment] 2016-06-06 12:21
So I guess that the output I have is the automatic printing of the log in the console. In this case you can forget my comment.

**Comment by tdurieux** [comment] 2016-06-06 12:28
This message is logged when you call `TypeRefefence<Object>.isSubtypeOf(TypeReference<SomeThing>)`. 
In `isSubtypeOf`, spoon creates a new `TypeReference` of the super class of the `Object`, but the super class of `Object` is `null` and thus a NPE is  thrown.

**Comment by GerardPaligot** [comment] 2016-06-13 09:21
@arnobl @remal @ttben we can close here?

**Comment by arnobl** [comment] 2016-06-13 12:57
I think so.

**Comment by GerardPaligot** [comment] 2016-06-13 13:47
Ok, feel free to open a new one (or re-open this one), if the bug is always there.

**Closed by GerardPaligot** 2016-06-13 13:47 UTC
