### ISSUE TITLE
[Bug]:  NoSourcePosition error

### ISSUE THREAD

**Issue by zqudm** [INRIA/spoon#4929] opened 2022-09-29 03:55 UTC
### Describe the bug

When i use spoon-core-6.0.0-jar-with-dependencies.jar, my program works well. However, when i use spoon-core-9.2.0-beta-8-jar-with-dependencies.jar, a failure occurred, that is,

_Exception in thread "main" java.lang.UnsupportedOperationException: PartialSourcePosition only contains a CompilationUnit
at spoon.reflect.cu.position.NoSourcePosition.getSourceEnd(NoSourcePosition.java:67)_

How to fix this error? Thanks !

The error is produced when analyzing the method  _compose_  listed below, and the key part  of the  analysis code is also shown below. 

### Source code you are trying to analyze/transform

```Java
package org.apache.commons.math3.analysis;
import org.apache.commons.math3.analysis.differentiation.DerivativeStructure;
import org.apache.commons.math3.analysis.differentiation.MultivariateDifferentiableFunction;
import org.apache.commons.math3.analysis.differentiation.MultivariateDifferentiableVectorFunction;
import org.apache.commons.math3.analysis.differentiation.UnivariateDifferentiableFunction;
import org.apache.commons.math3.analysis.function.Identity;
import org.apache.commons.math3.exception.DimensionMismatchException;
import org.apache.commons.math3.exception.NotStrictlyPositiveException;
import org.apache.commons.math3.exception.NumberIsTooLargeException;
import org.apache.commons.math3.exception.util.LocalizedFormats;

/**
 * Utilities for manipulating function objects.
 *
 * @since 3.0
 */
public class FunctionUtils {
    /**
     * Class only contains static methods.
     */
    private FunctionUtils() {}

    /**
     * Composes functions.
     * <p>
     * The functions in the argument list are composed sequentially, in the
     * given order.  For example, compose(f1,f2,f3) acts like f1(f2(f3(x))).</p>
     *
     * @param f List of functions.
     * @return the composite function.
     */
    public static UnivariateFunction compose(final UnivariateFunction ... f) {
        return new UnivariateFunction() {
            /** {@inheritDoc} */
            public double value(double x) {
                double r = x;
                for (int i = f.length - 1; i >= 0; i--) {
                    r = f[i].value(r);
                }
                return r;
            }
        };
    }
}
```

### Source code for your Spoon processing
```Java
public int getMin_length_code(CtMethod method) {
		int colmin = 99999999;
		if (method.getBody() != null && method.getBody().getStatements().size() != 0) {
			List<CtStatement> liststmt = method.getBody().getStatements();
			for (int i = 0; i < liststmt.size(); i++) {
				int collength = 0;
				if (liststmt.get(i).toString().indexOf("{") == -1 && liststmt.get(i).toString().indexOf("(") != 0) {
					if ((liststmt.get(i).getPosition().getSourceEnd()
							- liststmt.get(i).getPosition().getSourceStart()) > 2)
						collength = liststmt.get(i).getPosition().getSourceEnd()
								- liststmt.get(i).getPosition().getSourceStart();
				} else {
					collength = getMin_line_inStatment(liststmt.get(i));
				}
				if (collength < colmin)
					colmin = collength;
			}
		}
		if (colmin == 99999999)
			colmin = 0;
		return colmin;
	}

public int getMin_line_inStatment(CtStatement ste) {
		int min = 9999999;
		List<CtStatement> liststmt = ste.getElements(new TypeFilter(CtStatement.class));
		for (int i = liststmt.size() - 1; i > 1; i--) {
			int col = 0;
			if (liststmt.get(i).toString().indexOf("{") == -1 && liststmt.get(i).toString().indexOf("(") != 0) {                      
				if ((liststmt.get(i).getPosition().getSourceEnd() - liststmt.get(i).getPosition().getSourceStart()) > 2)
					col = liststmt.get(i).getPosition().getSourceEnd() - liststmt.get(i).getPosition().getSourceStart();
			}
			if (col < min)
				min = col;
		}
		return min;
	}
```

### Actual output

```Java
Exception in thread "main" java.lang.UnsupportedOperationException: PartialSourcePosition only contains a CompilationUnit
	at spoon.reflect.cu.position.NoSourcePosition.getSourceEnd(NoSourcePosition.java:65)
	at Version4.getMin_line_inStatment(Version4.java:170)
	at Version4.getMin_length_code(Version4.java:254)

```

### Expected output

```Java
No error.
```

### Spoon Version

spoon-core-9.2.0-beta-8-jar-with-dependencies.jar，spoon-core-6.0.0-jar-with-dependencies.jar

### JVM Version

11

### What operating system are you using?

ubuntu 16.0

**Comment by SirYwell** [comment] 2022-09-29 08:30
Could you also try with spoon 10.1.0 or spoon 10.2.0-beta-21?

How do you create the Launcher? Especially, how do you add the input resources?

Also, could you try to find out which statement is actually causing this and probably reduce the code to a minimal example?

**Comment by tenax66** [comment] 2023-02-12 09:29
I have probably reproduced the same error with the following target source code and processor, and I think this error occurred in relation to anonymous classes.
(spoon version: 10.2.0)

**Target source code:** 
```
package reproduce.target;

public class Reproduce {
	public Dummy reproduce() {
		return new Dummy() {
		};
	}

	class Dummy {
	}
}
```
**Processor:**
```
package reproduce.processor;

import java.util.List;

import spoon.processing.AbstractProcessor;
import spoon.reflect.code.CtStatement;
import spoon.reflect.declaration.CtMethod;
import spoon.reflect.visitor.filter.TypeFilter;

public class GetPositionProcessor extends AbstractProcessor<CtMethod<?>> {
	public void process(CtMethod<?> ctMethod) {
		List<CtStatement> statements = ctMethod.getElements(new TypeFilter<CtStatement>(CtStatement.class));
		for (CtStatement ctStatement : statements) {
			System.out.println(ctStatement.toString());
			System.out.println("start: " + ctStatement.getPosition().getSourceStart());
			System.out.println("end: " + ctStatement.getPosition().getSourceEnd());
		}
	}
}

```

I added the InputResource to the launcher and run it as follows:
```
        Launcher l = new Launcher();
        l.addInputResource("src/main/java/reproduce/target/Reproduce.java");
        l.addProcessor(new GetPositionProcessor());
        l.run();
```

And here is the output.
```
Exception in thread "main" java.lang.UnsupportedOperationException: PartialSourcePosition only contains a CompilationUnit
	at spoon.reflect.cu.position.NoSourcePosition.getSourceStart(NoSourcePosition.java:71)
	at reproduce.processor.GetPositionProcessor.process(GetPositionProcessor.java:15)
	at reproduce.processor.GetPositionProcessor.process(GetPositionProcessor.java:1)
```

I think the cause of this error is that the source position for the constructor of the anonymous class does not exist.
(In the example I gave, it is `Dummy() {}`.  The original source code defines an anonymous class for UnivariateFunction.)

This seems to be a reasonable behavior rather than a bug for me.

**Comment by SirYwell** [comment] 2023-02-12 12:13
Your analysis seems to be spot on, thanks!
As the body is correctly marked as `implicit`, this indeed isn't a bug. Filtering out implicit elements should do the trick.

**Comment by I-Al-Istannen** [comment] 2023-08-27 19:54
It sounds like this issue can be closed, feel free to reopen if you feel differently or this did not answer your question :)

**Closed by I-Al-Istannen** 2023-08-27 19:54 UTC
Labels: bug
