### ISSUE TITLE
regression started on Oct 10 2022

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#4956] opened 2022-10-12 11:23 UTC
One recent commit triggered a significant regression breaking our Jenkins CI:

* https://ci.inria.fr/sos/job/npefix/
* https://ci.inria.fr/sos/job/nopol/
* https://ci.inria.fr/sos/job/AssertFixer/

Who's available to look at it?

**Comment by SirYwell** [comment] 2022-10-12 11:32
Seems to be caused by the change in #4940. The EnumSet requires at least non-null element in the collection provided to `copyOf` to extract the underlying enum type. (cc @MartinWitt)

**Comment by MartinWitt** [comment] 2022-10-12 11:52
Proposed fix is in #4957.

**Comment by monperrus** [comment] 2022-10-14 16:54
I confirm that https://github.com/INRIA/spoon/pull/4957 fixes the regression, the Jenkins CI jobs are turning green again. 

Thanks a lot @MartinWitt  🙏️

**Closed** 2022-10-14 16:55 UTC
