### ISSUE TITLE
Positions lead to ArrayOutOfBoundException in real source

### ISSUE THREAD

**Issue by arturbosch** [INRIA/spoon#1143] opened 2017-01-21 07:51 UTC
We have a file 'CollectionHelper' in argouml test code for which spoon's source positions do not match the real source.

It's a relative small file with just one method and we try to obtain the source code of the method.

[file.zip](https://github.com/INRIA/spoon/files/720999/file.zip)

This is what spoon wants to give us:
```java
minimal update strategy and updating the
     * collection in place. This can be used with the JMI "live" semantic
     * collections to update the model in place. Order of processing is to first
     * remove all obsolete elements from the collection and then add all new
     * elements.
     * 
     * @param base
     *            the base collection to be updated
     * @param updates
     *            desired end state of collection
     */
    static void update(Collection base, Collection updates) {
        if (updates == null) {
            base.clear();
            return;
        }
        Collection toBeRemoved = new ArrayList();
        Collection toBeAdded = new ArrayList();

        Iterator oldIt = base.iterator();
        while (oldIt.hasNext()) {
            State s = (State) oldIt.next();
            if (!updates.contains(s)) {
                toBeRemoved.add(s);
            }
        }
        Iterator newIt = updates.iterator();
        while (newIt.hasNext()) {
            State s = (State) newIt.next();
            if (!base.contains(s)) {
                toBeAdded.add(s);
            }
        }

        base.removeAll(toBeRemoved);
        base.addAll(toBeAdded);
    }

}
```

**Comment by msteinbeck** [comment] 2017-01-28 12:42
We found that the issue is not Spoon related. Closing this one.

**Closed** 2017-01-30 08:21 UTC
Labels: bug
