### ISSUE TITLE
Problem with shadow class

### ISSUE THREAD

**Issue by mehdi-kaytoue** [INRIA/spoon#3172] opened 2019-11-14 12:07 UTC
Hello!

I use spoon for long time for one of our project, very recently only I came up with this exception, and I can't figure out what's happening. The error appears only when dealing with a very large code base, hence hard to debug and be more precise, but I can.

Does the fact that it involves javafx helps?

```
Exception in thread "main" spoon.support.SpoonClassNotFoundException: cannot create shadow class: javafx.scene.control.TextField
        at spoon.reflect.factory.TypeFactory.get(TypeFactory.java:552)
        at spoon.support.compiler.jdt.JDTImportBuilder.getOrLoadClass(JDTImportBuilder.java:143)
        at spoon.support.compiler.jdt.JDTImportBuilder.build(JDTImportBuilder.java:76)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.lambda$buildModel$1(JDTBasedSpoonCompiler.java:427)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.forEachCompilationUnit(JDTBasedSpoonCompiler.java:449)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:426)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:364)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:329)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:112)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:95)
        at spoon.Launcher.buildModel(Launcher.java:766)
        at fr.infologic.ia.parametrage.data.CopiloteModel.buildModel(CopiloteModel.java:147)
        at fr.infologic.ia.parametrage.Main.main(Main.java:64)
Caused by: java.lang.ExceptionInInitializerError
        at sun.misc.Unsafe.ensureClassInitialized(Native Method)
        at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
        at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
        at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
        at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
        at java.lang.reflect.Field.get(Field.java:393)
        at spoon.support.visitor.java.JavaReflectionTreeBuilder.visitField(JavaReflectionTreeBuilder.java:294)
        at spoon.support.visitor.java.JavaReflectionVisitorImpl.visitClass(JavaReflectionVisitorImpl.java:90)
        at spoon.support.visitor.java.JavaReflectionTreeBuilder.visitClass(JavaReflectionTreeBuilder.java:150)
        at spoon.support.visitor.java.JavaReflectionTreeBuilder.scan(JavaReflectionTreeBuilder.java:107)
        at spoon.reflect.factory.TypeFactory.get(TypeFactory.java:550)
        ... 12 more
Caused by: java.lang.IllegalStateException: Toolkit not initialized
        at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:273)
        at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:268)
        at com.sun.javafx.application.PlatformImpl.setPlatformUserAgentStylesheet(PlatformImpl.java:550)
        at com.sun.javafx.application.PlatformImpl.setDefaultPlatformUserAgentStylesheet(PlatformImpl.java:512)
        at javafx.scene.control.Control.<clinit>(Control.java:87)
        ... 23 more
```

**Comment by surli** [comment] 2019-11-14 12:09
Hi, it happened after upgrade to Spoon 8.0.0? Could be a duplicate of #3168

**Comment by mehdi-kaytoue** [comment] 2019-11-14 12:50
No on 7.5. Do you advise to go for 8.0 first ?

**Comment by mehdi-kaytoue** [comment] 2019-11-14 19:38
I switched back to 7.1 and it works.

**Comment by monperrus** [comment] 2019-12-02 07:53
Could you create a pull-request with a failing test case? Thanks!

**Comment by monperrus** [comment] 2020-02-13 08:45
staled, closing

**Closed by monperrus** 2020-02-13 08:45 UTC
Labels: bug

**Comment by loetifuss** [comment] 2020-06-18 06:15
I'm also experiencing this issue when analysing source code containing references to JavaFx classes on a Linux machine in a headless environment (i.e. no graphics library like GTK installed). 
When Spoon creates the shadow class the static initializer of the JavaFx class (in your case "javafx.scene.control.Control.<clinit>") is called and tries to load the JavaFx toolkit which fails on machines without the proper graphics setup.
As a consequence, currently you cannot analyse source code with JavaFx refs without having a graphics toolkit.

**Comment by monperrus** [comment] 2020-06-18 07:24
If you're in fullclasspath mode, that's normal. If you're in noclasspath mode it's a bug.

Are you already in noclasspath mode?
