### ISSUE TITLE
[ImportScanner] SpoonException: Cannot create MethodTypingContext for method declared in different ClassTypingContext

### ISSUE THREAD

**Issue by iMaysoN** [INRIA/spoon#2441] opened 2018-09-04 13:03 UTC
Preconditions:
### Test2.java
```
public class Test2 {
    private interface TestInt {
        String implementThis(String string);
    }

    //static, extends, implements and return method() - all that things needed
    static class Test3 extends ParentForTest implements TestInt {
        @Override
        public String implementThis(final String string) {
            return testMethod();
        }
    }
}
```
### ParentForTest.java
```
public class ParentForTest{
    public String testMethod() {
        return "";
    }
}
```
### Main.java
```
        final Launcher launcher = new Launcher();
        launcher.addInputResource("/path/Test2.java");
        launcher.buildModel();

        for (final CtType clazz : launcher.getModel().getAllTypes()) {
                ImportScanner importScanner = new ImportScannerImpl();
                importScanner.computeImports(class);
                Set<CtImport> allImports = importScanner.getAllImports();
        }
```
### Run

Exception in thread "main" spoon.SpoonException: Cannot create MethodTypingContext for method declared in different ClassTypingContext, was spoon.support.visitor.ClassTypingContext
	at spoon.support.visitor.MethodTypingContext.setMethod(MethodTypingContext.java:73)
	at spoon.support.visitor.ClassTypingContext.isSameSignature(ClassTypingContext.java:639)
	at spoon.support.visitor.ClassTypingContext.isSameSignature(ClassTypingContext.java:314)
	at spoon.support.reflect.declaration.CtTypeImpl$2.accept(CtTypeImpl.java:981)
	at spoon.support.reflect.declaration.CtTypeImpl$2.accept(CtTypeImpl.java:977)
	at spoon.reflect.visitor.chain.CtQueryImpl$OutputFunctionWrapper._accept(CtQueryImpl.java:468)
	at spoon.reflect.visitor.chain.CtQueryImpl$AbstractStep.accept(CtQueryImpl.java:318)
	at spoon.reflect.visitor.filter.AllTypeMembersFunction$1.accept(AllTypeMembersFunction.java:78)
	at spoon.reflect.visitor.filter.AllTypeMembersFunction$1.accept(AllTypeMembersFunction.java:73)
	at spoon.reflect.visitor.chain.CtQueryImpl$OutputFunctionWrapper._accept(CtQueryImpl.java:468)
	at spoon.reflect.visitor.chain.CtQueryImpl$AbstractStep.accept(CtQueryImpl.java:318)
	at spoon.reflect.visitor.filter.SuperInheritanceHierarchyFunction.sendResult(SuperInheritanceHierarchyFunction.java:375)
	at spoon.reflect.visitor.filter.SuperInheritanceHierarchyFunction.sendResultWithListener(SuperInheritanceHierarchyFunction.java:327)
	at spoon.reflect.visitor.filter.SuperInheritanceHierarchyFunction.visitSuperInterfaces(SuperInheritanceHierarchyFunction.java:314)
	at spoon.reflect.visitor.filter.SuperInheritanceHierarchyFunction.visitSuperClasses(SuperInheritanceHierarchyFunction.java:283)
	at spoon.reflect.visitor.filter.SuperInheritanceHierarchyFunction.apply(SuperInheritanceHierarchyFunction.java:265)
	at spoon.reflect.visitor.filter.SuperInheritanceHierarchyFunction.apply(SuperInheritanceHierarchyFunction.java:51)
	at spoon.reflect.visitor.chain.CtQueryImpl$LazyFunctionWrapper._accept(CtQueryImpl.java:501)
	at spoon.reflect.visitor.chain.CtQueryImpl$AbstractStep.accept(CtQueryImpl.java:318)
	at spoon.reflect.visitor.chain.CtQueryImpl.forEach(CtQueryImpl.java:104)
	at spoon.reflect.visitor.filter.AllTypeMembersFunction.apply(AllTypeMembersFunction.java:73)
	at spoon.reflect.visitor.filter.AllTypeMembersFunction.apply(AllTypeMembersFunction.java:36)
	at spoon.reflect.visitor.chain.CtQueryImpl$LazyFunctionWrapper._accept(CtQueryImpl.java:501)
	at spoon.reflect.visitor.chain.CtQueryImpl$AbstractStep.accept(CtQueryImpl.java:318)
	at spoon.reflect.visitor.chain.CtQueryImpl.forEach(CtQueryImpl.java:104)
	at spoon.support.reflect.declaration.CtTypeImpl.getAllMethods(CtTypeImpl.java:977)
	at spoon.reflect.visitor.ImportScannerImpl.isInCollisionWithLocalMethod(ImportScannerImpl.java:562)
	at spoon.reflect.visitor.ImportScannerImpl.addMethodImport(ImportScannerImpl.java:585)
	at spoon.reflect.visitor.ImportScannerImpl.visitCtExecutableReference(ImportScannerImpl.java:109)
	at spoon.support.reflect.reference.CtExecutableReferenceImpl.accept(CtExecutableReferenceImpl.java:83)
	at spoon.reflect.visitor.ImportScannerImpl.scan(ImportScannerImpl.java:146)
	at spoon.reflect.visitor.ImportScannerImpl.visitCtInvocation(ImportScannerImpl.java:220)
	at spoon.support.reflect.code.CtInvocationImpl.accept(CtInvocationImpl.java:55)
	at spoon.reflect.visitor.ImportScannerImpl.scan(ImportScannerImpl.java:146)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:173)
	at spoon.reflect.visitor.CtScanner.visitCtReturn(CtScanner.java:678)
	at spoon.support.reflect.code.CtReturnImpl.accept(CtReturnImpl.java:36)
	at spoon.reflect.visitor.ImportScannerImpl.scan(ImportScannerImpl.java:146)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:173)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:147)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:302)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:68)
	at spoon.reflect.visitor.ImportScannerImpl.scan(ImportScannerImpl.java:146)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:173)
	at spoon.reflect.visitor.CtScanner.visitCtMethod(CtScanner.java:559)
	at spoon.support.reflect.declaration.CtMethodImpl.accept(CtMethodImpl.java:72)
	at spoon.reflect.visitor.ImportScannerImpl.scan(ImportScannerImpl.java:146)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:173)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:147)
	at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:338)
	at spoon.reflect.visitor.ImportScannerImpl.visitCtClass(ImportScannerImpl.java:206)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:67)
	at spoon.reflect.visitor.ImportScannerImpl.scan(ImportScannerImpl.java:146)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:173)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:147)
	at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:338)
	at spoon.reflect.visitor.ImportScannerImpl.visitCtClass(ImportScannerImpl.java:206)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:67)
	at spoon.reflect.visitor.ImportScannerImpl.scan(ImportScannerImpl.java:146)
	at spoon.reflect.visitor.ImportScannerImpl.computeImports(ImportScannerImpl.java:259)
	at spoon.wrikeparser.ParseImports.main(ParseImports.java:79)
```

**Comment by monperrus** [comment] 2018-09-06 15:03
Thanks a lot for the detailed bug report.

Would you create a pull request with the failing test case?

**Comment by monperrus** [comment] 2018-09-17 19:07
@pvojtechovsky would you have a look at this bug?

**Comment by iMaysoN** [comment] 2018-09-17 19:11
not so simple as i expected, based on files place and paths in launcher.addInputResource :(

**Comment by pvojtechovsky** [comment] 2018-09-17 19:39
@iMaysoN Is the problem reproducible on latest spoon snapshot? The provided stacktrace doesn't matches with latest spoon sources, so you tried an older version.

**Comment by pvojtechovsky** [comment] 2018-09-25 18:28
@iMaysoN. Can we close this problem?

**Comment by monperrus** [comment] 2018-10-01 18:43
@iMaysoN Can you close this issue if it's fixed in the latest version?

**Comment by monperrus** [comment] 2018-12-01 18:48
no activity, closing. don't hesitate to reopen.

**Closed by monperrus** 2018-12-01 18:48 UTC
Labels: bug

**Comment by ITWOI** [comment] 2019-04-04 03:36
Hi,

I also face the exception, which is "Cannot create MethodTypingContext for method declared in different ClassTypingContext".  
The reproduce codes are in my repo: https://github.com/ITWOI/spoon-example.

The stack tracks are as follows:

```
Exception in thread "main" spoon.SpoonException: Cannot create MethodTypingContext for method declared in different ClassTypingContext
        at spoon.support.visitor.MethodTypingContext.setMethod(MethodTypingContext.java:74)
        at spoon.support.visitor.ClassTypingContext.isSameSignature(ClassTypingContext.java:639)
        at spoon.support.visitor.ClassTypingContext.isSameSignature(ClassTypingContext.java:314)
        at spoon.support.reflect.declaration.CtTypeImpl$2.accept(CtTypeImpl.java:916)
        at spoon.support.reflect.declaration.CtTypeImpl$2.accept(CtTypeImpl.java:912)
        at spoon.reflect.visitor.chain.CtQueryImpl$OutputFunctionWrapper._accept(CtQueryImpl.java:470)
        at spoon.reflect.visitor.chain.CtQueryImpl$AbstractStep.accept(CtQueryImpl.java:318)
        at spoon.reflect.visitor.filter.AllTypeMembersFunction$1.accept(AllTypeMembersFunction.java:107)
        at spoon.reflect.visitor.filter.AllTypeMembersFunction$1.accept(AllTypeMembersFunction.java:90)
        at spoon.reflect.visitor.chain.CtQueryImpl$OutputFunctionWrapper._accept(CtQueryImpl.java:470)
        at spoon.reflect.visitor.chain.CtQueryImpl$AbstractStep.accept(CtQueryImpl.java:318)
        at spoon.reflect.visitor.filter.SuperInheritanceHierarchyFunction.sendResult(SuperInheritanceHierarchyFunction.java:371)
        at spoon.reflect.visitor.filter.SuperInheritanceHierarchyFunction.sendResultWithListener(SuperInheritanceHierarchyFunction.java:323)
        at spoon.reflect.visitor.filter.SuperInheritanceHierarchyFunction.visitSuperInterfaces(SuperInheritanceHierarchyFunction.java:310)
        at spoon.reflect.visitor.filter.SuperInheritanceHierarchyFunction.visitSuperClasses(SuperInheritanceHierarchyFunction.java:279)
        at spoon.reflect.visitor.filter.SuperInheritanceHierarchyFunction.apply(SuperInheritanceHierarchyFunction.java:261)
        at spoon.reflect.visitor.filter.SuperInheritanceHierarchyFunction.apply(SuperInheritanceHierarchyFunction.java:47)
        at spoon.reflect.visitor.chain.CtQueryImpl$LazyFunctionWrapper._accept(CtQueryImpl.java:503)
        at spoon.reflect.visitor.chain.CtQueryImpl$AbstractStep.accept(CtQueryImpl.java:318)
        at spoon.reflect.visitor.chain.CtQueryImpl.forEach(CtQueryImpl.java:104)
        at spoon.reflect.visitor.filter.AllTypeMembersFunction.apply(AllTypeMembersFunction.java:90)
        at spoon.reflect.visitor.filter.AllTypeMembersFunction.apply(AllTypeMembersFunction.java:39)
        at spoon.reflect.visitor.chain.CtQueryImpl$LazyFunctionWrapper._accept(CtQueryImpl.java:503)
        at spoon.reflect.visitor.chain.CtQueryImpl$AbstractStep.accept(CtQueryImpl.java:318)
        at spoon.reflect.visitor.chain.CtQueryImpl.forEach(CtQueryImpl.java:104)
        at spoon.support.reflect.declaration.CtTypeImpl.getAllMethods(CtTypeImpl.java:912)
        at fileLocProcessor.process(fileLocProcessor.java:42)
        at fileLocProcessor.process(fileLocProcessor.java:17)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:81)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:176)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:150)
        at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:341)
        at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:67)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:184)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:77)
        at spoon.support.QueueProcessingManager.process(QueueProcessingManager.java:129)
        at Main.returnBuggyLoc(Main.java:45)
        at Main.main(Main.java:84)
```

Would you please help me to figure our the reason? 

Thanks.
