### ISSUE TITLE
noclasspath mode is used but it shouldn't be the case

### ISSUE THREAD

**Issue by vmassol** [INRIA/spoon#3325] opened 2020-04-14 08:06 UTC
Hi,

1) I see that https://github.com/SpoonLabs/spoon-maven-plugin/blob/master/src/main/java/fr/inria/gforge/spoon/SpoonMojoGenerate.java#L71 sets the noclasspath mode to false by default
2) I also put `<noClasspath>false</noClasspath>` in my spoon plugin config.

Yet I get:

```
[INFO] --- spoon-maven-plugin:3.2:check (spoon-main) @ xwiki-commons-component-api ---
[INFO] Spoon report directory: /Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-api/target/spoon-maven-plugin
[INFO] Generate spoon without a spoon.xml file.
[INFO] Running spoon with classpath:
[INFO] file:/Applications/apache-maven-3.6.2/boot/plexus-classworlds-2.6.0.jar
[INFO] Running in NOCLASSPATH mode (doc: http://spoon.gforge.inria.fr/launcher.html).
[INFO] Running spoon with parameters:
[INFO] [--level, INFO, -i, /Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-api/src/main/java:/Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-api/target/generated-sources/annotations, -o, /Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-api/target/generated-sources/spoon, --compliance, 8, --source-classpath, /Users/vmassol/.m2/repository/org/xwiki/commons/xwiki-commons-stability/12.3-SNAPSHOT/xwiki-commons-stability-12.3-SNAPSHOT.jar:/Users/vmassol/.m2/repository/org/xwiki/commons/xwiki-commons-text/12.3-SNAPSHOT/xwiki-commons-text-12.3-SNAPSHOT.jar:/Users/vmassol/.m2/repository/org/apache/commons/commons-lang3/3.10/commons-lang3-3.10.jar:/Users/vmassol/.m2/repository/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar:/Users/vmassol/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:, -p, org.xwiki.tool.spoon.ForbiddenInvocationProcessor:org.xwiki.tool.spoon.ComponentAnnotationProcessor, --output-type, nooutput]
[INFO] Running in NOCLASSPATH mode (doc: http://spoon.gforge.inria.fr/launcher.html).
[INFO] Spoon version 8.1.0
[INFO] running Spoon...
[INFO] start processing...
[INFO] org.xwiki.tool.spoon.ForbiddenInvocationProcessor
[INFO] org.xwiki.tool.spoon.ComponentAnnotationProcessor
[INFO] end of processing: 
[INFO] no errors, no warnings
[INFO] 
```

Any idea?

Thanks

**Comment by surli** [comment] 2020-04-14 08:11
That's a serious regression caused by https://github.com/INRIA/spoon/pull/3242/files#diff-aa0cb99e88cfef20a12f16223180b19eL377 basically we removed the noclasspath mode, but we never refactor the spoon-maven-plugin for it... 

We should really incorporate the Spoon Maven Plugin in this repository and test it along with Spoon so we could spot those regressions.

**Comment by monperrus** [comment] 2020-04-15 13:58
fixed in https://github.com/SpoonLabs/spoon-maven-plugin/pull/67/files#diff-6e04d2bbe21096d9338f81f30440c334

**Comment by vmassol** [comment] 2020-04-15 14:19
Great, thanks @monperrus !

**Closed** 2020-04-16 08:34 UTC
Labels: bug, spoon-maven-plugin
