### ISSUE TITLE
NPE when initially processing sources on large GWT project

### ISSUE THREAD

**Issue by sjd78** [INRIA/spoon#550] opened 2016-03-07 16:35 UTC
I'm using spoon to help do some static code transform against a large GWT project (ovirt-engine - git://gerrit.ovirt.org/ovirt-engine).  Before my code runs, the Launcher throws an NPE:

```
Exception in thread "main" java.lang.NullPointerException
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:228)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:481)
	at spoon.Launcher.buildModel(Launcher.java:682)
	at spoon.Launcher.run(Launcher.java:634)
```

I tracked down the issue, and the CompilationUnitDeclaration[] returned from TreeBuilderCompiler contains a large number of consecutive null elements at the end of the array.  If I change TreeBuilderCompiler.buildUnits() to return an array bound in length by "this.totalUnits" everything is well.

I plan on submitting a pull request against the stable branch with this simple fix.

**Comment by GerardPaligot** [comment] 2016-03-08 16:23
Can you give us an example to know how to reproduce your bug? I tried to apply Spoon due to the Spoon Maven Plugin. Even if I can't apply Spoon on all modules of your project because you have some private dependencies, everything seems to work fine.

Maybe, you can create a test case in your PR to highlight the bug?

**Comment by sjd78** [comment] 2016-03-09 21:03
I'll take another look.  I'm using the Launcher directly in code instead of the maven plugin, but I've encountered the issue both ways.  Hopefully I can get it to reliably break.

The tool I'm building is ding a one time transform of the codebase, so running it continulily with the maven plugin is a bit overkill.

I'll report back if I can get it breaking

**Comment by sjd78** [comment] 2016-03-11 18:51
I can only consistently recreate the compile NPE problem running spoon 5.0.2 under eclipse's m2e maven exec:exec launcher.  Standard spoon 5.0.2 works with maven exec:exec from the command line.  The only difference is the classpath.  The eclipse launcher resolves my projects to the eclipse workspace while the command line call resolves my projects to their installed location in my local .m2 repository.  With my patch applied, spoon works in both instances.

I'll post an example the best I can soon.

**Comment by GerardPaligot** [comment] 2016-03-15 14:07
Ok, thanks to the eclipse maven plugin... :)

I commented your PR.

**Comment by GerardPaligot** [comment] 2016-03-21 14:39
PR merged. Thanks.

**Closed by GerardPaligot** 2016-03-21 14:39 UTC
