### ISSUE TITLE
How to extract an AST from Spoon in Scala?

### ISSUE THREAD

**Issue by ontologiae** [INRIA/spoon#2710] opened 2018-10-22 16:56 UTC
Hi, I'm trying and I failed to extract an AST from Spoon to as a Scala case class, in other word a Algeabric Data Type. I used to express the Grammar like this.
For instance, If I represent 
```
 int n() {
        m();
        return 7;
}
```

I can represent it as follow :

```
case class MyCtMethod( params : List[MyCtParameters], returns : MyCtTypeRef, body : List[MyCtStatement])
trait Statements
case class MyCtBlock( statements : List[MyCtStatement]) extends Statements
case class MyCtInvocation, MyIfStatementJava, MyForStatementJava, MyCtReturn, whatever...
```

So, my little function would be represented as :

```
MyCtMethod( params = 
		 List.empty, 
		returns = MyCtTypeRef(IntType), 
		body = List(MyCtInvocation("org.truc.machin.m"), MyCtReturn( ...)) 
		)
```

Here's an example of how I'm stuck : 

```
val  l = Launcher.parseClass("package org.mypackage; class A { void m() { System.out.println(\"yeah\");} int n() { m(); return 7;}   }");
val n = l.getMethods.asScala.toList.apply(1)
n: spoon.reflect.declaration.CtMethod[_] =
int n() {
    {
        m();
        return 7;
    }
}


n.getBody.getStatements.get(0)
res2: spoon.reflect.code.CtStatement =
{
    m();
    return 7;
}
```

I can't go further : Impossible to extract my two statements : there's no method in CtStatement to get the code inside the body, and it seems it's everywhere like this in this lib

So, is there a way to extract an AST ? My goal is to make with a walker function, as I did with Eclipse JDT librairy

**Comment by pvojtechovsky** [comment] 2018-10-22 18:05
> there's no method in CtStatement to get the code inside the body

You have to cast CtStatement  to CtBlock, then you get access to internal statements.

you wrote:
```
int n() w{ m(); return 7;}
```
what is the `w` in the code fragment copied from your example? May be it confused java compiler?

**Comment by ontologiae** [comment] 2018-10-23 12:55
It's corrected my mistake, thank you, I solved my first problem, permit to make one step, and I'm know stuck with another problem : like you said, I'm forced to cast.

```
scala> val n = l.getMethods.asScala.toList.apply(1)
n: spoon.reflect.declaration.CtMethod[_] =
int n() {
    m();
    return 7;
}

scala> n.getBody.getStatements
res36: java.util.List[spoon.reflect.code.CtStatement] = [m(), return 7]

scala> n.getBody.getStatements.get(0)
res38: spoon.reflect.code.CtStatement = m()
```

How can I know that it's not a CtStatement, but a CtInvocation ?
How can I walk through the tree, if the walker can't know the right type it has ?

**Comment by pvojtechovsky** [comment] 2018-10-23 13:30
See CtScanner. It is a Spoon AST tree walker

**Comment by monperrus** [comment] 2018-10-28 10:36
Please close this issue if this problem is solved, and don't hesitate to create a new issue if you encounter a new problem.

**Comment by ontologiae** [comment] 2018-11-02 13:44
It is not closed because the visitor pattern is absolutely unusable in Scala : you cannot recall your function in a recursive way to build an AST. CtScanner is unusable. It's made for the Java world.
So I don't know how to do with these answer.

**Comment by pvojtechovsky** [comment] 2018-11-02 21:10
> unusable in Scala

I know really only little things about Scala but I am sure that problem is not in CtScanner or impossibility to use it in Scala. I guess the problem is that you expect a different behavior - and this behavior is not the one which fits to idea behind CtScanner. 
The concept of a CtScanner is a "visitor pattern", which can be applied to processing of Abstract syntax tree.

> How can I know that it's not a CtStatement, but a CtInvocation ?
in java it is 
```java
CtStatement stmt = ... 
if (stmt instanceof CtInvocation) {
//it is invocation
else {
//it is any other statement
}
```
In Scala? May be this helps? https://stackoverflow.com/questions/8561898/how-to-do-an-instanceof-check-with-scalatest.

> How can I walk through the tree, if the walker can't know the right type it has ?

Walker is CtScanner and CtScanner of course knows what node it actually scans. So it visits all the nodes of the AST and will call appropriate methods of CtScanner, which you have to override in Scala.

I know that visitor pattern needs some time to understand, but it is really powerful concept which we use to solve 90% of code analyzing problems.

Good luck! ;-)

**Comment by monperrus** [comment] 2019-09-02 07:39
Related #3082

**Closed by monperrus** 2019-09-02 07:39 UTC
Labels: question

**Comment by ontologiae** [comment] 2019-12-18 22:35
I found a way : example


```
val res = e match {
			case ctB : CtBlock[_] => JavaCtBlock(uid, ctB.getStatements.asScala.toList.map{ elem => descendStatement( elem)}, 
						   														 genereSourcePosition(ctB.getPosition))
			case ctC : CtDo 		=> JavaCtDo (uid,descendStatement(ctC.getBody), descendExpression(ctC.getLoopingExpression),
																	 			   genereSourcePosition(ctC.getPosition)
																			)
 			case ctB : CtBreak => JavaCtBreak(uid, genereSourcePosition(ctB.getPosition))

			case ctD : CtContinue 		=> JavaCtContinue(uid,  genereSourcePosition(ctD.getPosition))

			case ctCa: CtCatch 		=> JavaCtCatch(uid, descendStatement(ctCa.getBody),
										genereSourcePosition(ctCa.getPosition)
								      )

			case ctI : CtIf 		=> JavaCtIf(uid, descendExpression(ctI.getCondition),
									     descendStatement(ctI.getThenStatement.asInstanceOf[CtStatement]), 
						   			     descendStatement(ctI.getElseStatement.asInstanceOf[CtStatement]), 
								 genereSourcePosition(ctI.getPosition))
	
```

**Comment by monperrus** [comment] 2019-12-21 14:55
thanks for sharing.
