### ISSUE TITLE
[Bug]: Model building with throws clause crashes with ParentNotInitializedException using Spoon 9

### ISSUE THREAD

**Issue by zqudm** [INRIA/spoon#5004] opened 2022-11-09 13:35 UTC
### Describe the bug

When code contains throws or throw statement, building model crashes.

```
public byte[] getBytes(String name, String suffix) throws IOException {
    DataInputStream dis = null;
    try {
        InputStream is = getInputStream(name, suffix);
        if (is == null) {
            throw new IOException((("Couldn't find: " + name) + suffix));
        }
        dis = new DataInputStream(is);
        byte[] bytes = new byte[is.available()];
        dis.readFully(bytes);
        return bytes;
    } finally {
        if (dis != null) {
            dis.close();
        }
    }
}

```

the following error occurs.

Exception in thread "main" spoon.reflect.declaration.ParentNotInitializedException: parent not initialized for IOException(class spoon.support.reflect.reference.CtTypeReferenceImpl)
spoon.Launcher.buildModel(Launcher.java:781)

### Spoon Version

9.1.0

### JVM Version

11

### What operating system are you using?

ubuntu

**Comment by SirYwell** [comment] 2022-11-09 14:15
Hi,
I'm unable to reproduce the issue with spoon 10.2.0. Could you try updating to see if your problem persists?

**Comment by zqudm** [comment] 2022-11-13 10:08
With spoon 10.2.0,  no error occurs!

**Comment by I-Al-Istannen** [comment] 2022-11-14 11:17
I think we can consider this fixed then and close the issue? Feel free to comment and re-open if you disagree :)

**Closed by I-Al-Istannen** 2022-11-14 11:17 UTC
Labels: bug, information-needed
